project:
  type: website
  output-dir: docs

website:
  title: "Météo Montpellier"
  navbar:
    tools: 
      - icon: github
        href: https://github.com/pierre-ed-ds/Weather
        text: GitHub
    left:
      - href: index.qmd
        text: Prévisions
      - about.qmd

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true

schedules:
- cron: '0 0,12 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - main
    - release

editor: visual

